# Form implementation generated from reading ui file 'Studentstuff.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SecWindow(object):
    def setupUi(self, SecWindow):
        SecWindow.setObjectName("SecWindow")
        SecWindow.resize(287, 504)
        self.centralwidget = QtWidgets.QWidget(parent=SecWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sportedit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.sportedit.setGeometry(QtCore.QRect(220, 90, 31, 20))
        self.sportedit.setObjectName("sportedit")
        self.precaledit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.precaledit.setGeometry(QtCore.QRect(220, 130, 31, 20))
        self.precaledit.setObjectName("precaledit")
        self.computersciedit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.computersciedit.setGeometry(QtCore.QRect(220, 170, 31, 20))
        self.computersciedit.setObjectName("computersciedit")
        self.historyedit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.historyedit.setGeometry(QtCore.QRect(220, 210, 31, 20))
        self.historyedit.setObjectName("historyedit")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 90, 51, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 130, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 170, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 210, 47, 13))
        self.label_4.setObjectName("label_4")
        self.done = QtWidgets.QPushButton(parent=self.centralwidget)
        self.done.setGeometry(QtCore.QRect(40, 390, 75, 23))
        self.done.setObjectName("done")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(80, -10, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 60, 47, 13))
        self.label_6.setObjectName("label_6")
        self.nameedit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.nameedit.setGeometry(QtCore.QRect(100, 60, 151, 20))
        self.nameedit.setObjectName("nameedit")
        self.notepad = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.notepad.setGeometry(QtCore.QRect(30, 250, 221, 131))
        self.notepad.setObjectName("notepad")
        self.warning_error = QtWidgets.QLabel(parent=self.centralwidget)
        self.warning_error.setGeometry(QtCore.QRect(30, 430, 201, 20))
        self.warning_error.setText("")
        self.warning_error.setObjectName("warning_error")
        self.butt_del = QtWidgets.QPushButton(parent=self.centralwidget)
        self.butt_del.setGeometry(QtCore.QRect(170, 390, 75, 23))
        self.butt_del.setObjectName("butt_del")
        SecWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=SecWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 287, 21))
        self.menubar.setObjectName("menubar")
        SecWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=SecWindow)
        self.statusbar.setObjectName("statusbar")
        SecWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SecWindow)
        QtCore.QMetaObject.connectSlotsByName(SecWindow)

    def retranslateUi(self, SecWindow):
        _translate = QtCore.QCoreApplication.translate
        SecWindow.setWindowTitle(_translate("SecWindow", "MainWindow"))
        self.label.setText(_translate("SecWindow", "Sports"))
        self.label_2.setText(_translate("SecWindow", "Pre-cal"))
        self.label_3.setText(_translate("SecWindow", "Computer Sci"))
        self.label_4.setText(_translate("SecWindow", "History"))
        self.done.setText(_translate("SecWindow", "Done"))
        self.label_5.setText(_translate("SecWindow", "Report card"))
        self.label_6.setText(_translate("SecWindow", "Name"))
        self.notepad.setHtml(_translate("SecWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Notes:</p></body></html>"))
        self.butt_del.setText(_translate("SecWindow", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SecWindow = QtWidgets.QMainWindow()
    ui = Ui_SecWindow()
    ui.setupUi(SecWindow)
    SecWindow.show()
    sys.exit(app.exec())
